import 'package:flutter/material.dart';

class AppPresets {
  static const List<Map<String, dynamic>> darkPresets = [
    {
      'name': 'Midnight Blue',
      'colors': {
        'primary': Color(0xFF60A5FA),
        'background': Color(0xFF0B1120),
        'card': Color(0xFF1E293B),
        'textPrimary': Color(0xFFF8FAFC),
        'textSecondary': Color(0xFF94A3B8),
        'buttonPrimary': Color(0xFF60A5FA),
        'buttonHover': Color(0xFF3B82F6),
        'border': Color(0xFF334155),
        'success': Color(0xFF34D399),
        'warning': Color(0xFFFBBF24),
        'danger': Color(0xFFF87171),
      },
    },
    {
      'name': 'Matrix Code',
      'colors': {
        'primary': Color(0xFF4ADE80),
        'background': Color(0xFF000000),
        'card': Color(0xFF061A0B),
        'textPrimary': Color(0xFFE2F8E7),
        'textSecondary': Color(0xFF63B978),
        'buttonPrimary': Color(0xFF22C55E),
        'buttonHover': Color(0xFF16A34A),
        'border': Color(0xFF14532D),
        'success': Color(0xFF4ADE80),
        'warning': Color(0xFFEAB308),
        'danger': Color(0xFFEF4444),
      },
    },
    {
      'name': 'Vampire Night',
      'colors': {
        'primary': Color(0xFFC084FC),
        'background': Color(0xFF0F0A15),
        'card': Color(0xFF21152C),
        'textPrimary': Color(0xFFFAEDFE),
        'textSecondary': Color(0xFFAFA3B8),
        'buttonPrimary': Color(0xFFA855F7),
        'buttonHover': Color(0xFF9333EA),
        'border': Color(0xFF3B264A),
        'success': Color(0xFF10B981),
        'warning': Color(0xFFF59E0B),
        'danger': Color(0xFFBE123C),
      },
    },
    {
      'name': 'Coffee House',
      'colors': {
        'primary': Color(0xFFD6D3D1),
        'background': Color(0xFF1C1917),
        'card': Color(0xFF292524),
        'textPrimary': Color(0xFFF5F5F4),
        'textSecondary': Color(0xFFA8A29E),
        'buttonPrimary': Color(0xFFA8A29E),
        'buttonHover': Color(0xFF78716C),
        'border': Color(0xFF44403C),
        'success': Color(0xFF14B8A6),
        'warning': Color(0xFFD97706),
        'danger': Color(0xFFDC2626),
      },
    },
    {
      'name': 'Cyberpunk',
      'colors': {
        'primary': Color(0xFFF472B6),
        'background': Color(0xFF09090B),
        'card': Color(0xFF18181B),
        'textPrimary': Color(0xFFFFFFFF),
        'textSecondary': Color(0xFFA1A1AA),
        'buttonPrimary': Color(0xFFEC4899),
        'buttonHover': Color(0xFFDB2777),
        'border': Color(0xFF27272A),
        'success': Color(0xFF10B981),
        'warning': Color(0xFFF59E0B),
        'danger': Color(0xFFE11D48),
      },
    },
  ];

  static const List<Map<String, dynamic>> lightPresets = [
    {
      'name': 'Ocean Breeze',
      'colors': {
        'primary': Color(0xFF0EA5E9),
        'background': Color(0xFFF0F9FF),
        'card': Color(0xFFFFFFFF),
        'textPrimary': Color(0xFF0F172A),
        'textSecondary': Color(0xFF64748B),
        'buttonPrimary': Color(0xFF0284C7),
        'buttonHover': Color(0xFF0369A1),
        'border': Color(0xFFE0F2FE),
        'success': Color(0xFF10B981),
        'warning': Color(0xFFF59E0B),
        'danger': Color(0xFFEF4444),
      },
    },
    {
      'name': 'Forest Walk',
      'colors': {
        'primary': Color(0xFF10B981),
        'background': Color(0xFFF0FDF4),
        'card': Color(0xFFFFFFFF),
        'textPrimary': Color(0xFF064E3B),
        'textSecondary': Color(0xFF475569),
        'buttonPrimary': Color(0xFF059669),
        'buttonHover': Color(0xFF047857),
        'border': Color(0xFFDCFCE7),
        'success': Color(0xFF10B981),
        'warning': Color(0xFFD97706),
        'danger': Color(0xFFDC2626),
      },
    },
    {
      'name': 'Sunset Glow',
      'colors': {
        'primary': Color(0xFFF59E0B),
        'background': Color(0xFFFFF7ED),
        'card': Color(0xFFFFFFFF),
        'textPrimary': Color(0xFF431407),
        'textSecondary': Color(0xFF78350F),
        'buttonPrimary': Color(0xFFEA580C),
        'buttonHover': Color(0xFFC2410C),
        'border': Color(0xFFFFEDD5),
        'success': Color(0xFF059669),
        'warning': Color(0xFFD97706),
        'danger': Color(0xFFE11D48),
      },
    },
    {
      'name': 'Lavender Dream',
      'colors': {
        'primary': Color(0xFF8B5CF6),
        'background': Color(0xFFFFF1F2),
        'card': Color(0xFFFFFFFF),
        'textPrimary': Color(0xFF2E1065),
        'textSecondary': Color(0xFF5B21B6),
        'buttonPrimary': Color(0xFF7C3AED),
        'buttonHover': Color(0xFF6D28D9),
        'border': Color(0xFFF3E8FF),
        'success': Color(0xFF10B981),
        'warning': Color(0xFFF59E0B),
        'danger': Color(0xFFF43F5E),
      },
    },
    {
      'name': 'Corporate Blue',
      'colors': {
        'primary': Color(0xFF1E40AF),
        'background': Color(0xFFF8FAFC),
        'card': Color(0xFFFFFFFF),
        'textPrimary': Color(0xFF0F172A),
        'textSecondary': Color(0xFF475569),
        'buttonPrimary': Color(0xFF1E3A8A),
        'buttonHover': Color(0xFF172554),
        'border': Color(0xFFE2E8F0),
        'success': Color(0xFF16A34A),
        'warning': Color(0xFFD97706),
        'danger': Color(0xFFDC2626),
      },
    },
  ];
}
